// test/helpers/test_helpers.dart
// Common helpers for the ExamBoost Togo test suite.
//
// Provides:
//   - initHiveForTests() : Hive init in a temp dir + adapter registration.
//   - closeHiveAfterTests() : clean teardown.
//   - createTestUser() : AppUser with preset BKT values.
//   - createTestQuestion() : Question with preset IRT params.
//   - createTestReviewCard() : ReviewCard with preset SM-2 state.
//   - pumpAppWithProviders() : pump a widget wrapped in MultiProvider + MaterialApp.
//
// NOTE: All model adapters (QuestionAdapter, ReviewCardAdapter, AppUserAdapter,
// QuestionTypeAdapter) are generated by `dart run build_runner build` from the
// @HiveType annotations in lib/models/*.dart. Run build_runner before tests.

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:hive/hive.dart';
import 'package:provider/provider.dart';

import 'package:examboost_togo/models/question.dart';
import 'package:examboost_togo/models/review_card.dart';
import 'package:examboost_togo/models/user.dart';
import 'package:examboost_togo/providers/user_provider.dart';
import 'package:examboost_togo/services/question_service.dart';
import 'package:examboost_togo/services/srs_service.dart';

import 'mock_services.dart';

// ─── Hive lifecycle ────────────────────────────────────────────────

/// Initialize Hive in a temp directory and register all model adapters.
/// Call this in `setUpAll` for tests that touch Hive boxes.
///
/// Safe to call multiple times: adapter registration is guarded by
/// `Hive.isAdapterRegistered`.
Directory initHiveForTests() {
  final tempDir = Directory.systemTemp.createTempSync('examboost_test_');
  Hive.init(tempDir.path);

  if (!Hive.isAdapterRegistered(0)) Hive.registerAdapter(QuestionAdapter());
  if (!Hive.isAdapterRegistered(1)) Hive.registerAdapter(QuestionTypeAdapter());
  if (!Hive.isAdapterRegistered(2)) Hive.registerAdapter(ReviewCardAdapter());
  if (!Hive.isAdapterRegistered(3)) Hive.registerAdapter(AppUserAdapter());

  return tempDir;
}

/// Close all Hive boxes and delete the temp directory.
/// Call this in `tearDownAll`.
Future<void> closeHiveAfterTests() async {
  await Hive.close();
}

// ─── Factory helpers ───────────────────────────────────────────────

/// Build a test AppUser with sensible defaults.
///
/// - [id] defaults to 'test-user'.
/// - [bktMaitrise] defaults to an empty map (use [withBkt] for preset values).
/// - [niveauScolaire] defaults to '3eme'.
AppUser createTestUser({
  String id = 'test-user',
  String nom = 'Doe',
  String prenom = 'Jane',
  String niveauScolaire = '3eme',
  String? serie,
  Map<String, double>? bktMaitrise,
  double? thetaIrt,
}) {
  return AppUser(
    id: id,
    nom: nom,
    prenom: prenom,
    niveauScolaire: niveauScolaire,
    serie: serie,
    dateInscription: DateTime(2026, 1, 1),
    bktMaitrise: bktMaitrise ?? <String, double>{},
    thetaIrt: thetaIrt,
  );
}

/// Build a test Question with sensible defaults.
Question createTestQuestion({
  String id = 'TG-BEPC-MATHS-2022-Q01',
  String enonce = 'Résoudre : 3x + 7 = 22',
  String reponse = 'x = 5',
  String? explication = 'On isole x en soustrayant 7 puis en divisant par 3.',
  String matiere = 'Mathématiques',
  String chapitre = 'Équations du premier degré',
  String competenceId = 'TG-MATHS-EQ1D-001',
  String examen = 'BEPC',
  String? serie,
  int? annee = 2022,
  QuestionType type = QuestionType.calcul,
  List<String>? choix,
  int? points = 4,
  double? irtA = 1.0,
  double? irtB = -0.5,
  double? irtC = 0.0,
  bool irtCalibrated = false,
}) {
  return Question(
    id: id,
    enonce: enonce,
    reponse: reponse,
    explication: explication,
    matiere: matiere,
    chapitre: chapitre,
    competenceId: competenceId,
    examen: examen,
    serie: serie,
    annee: annee,
    type: type,
    choix: choix,
    points: points,
    irtA: irtA,
    irtB: irtB,
    irtC: irtC,
    irtCalibrated: irtCalibrated,
  );
}

/// Build a test ReviewCard with sensible defaults.
ReviewCard createTestReviewCard({
  String userId = 'test-user',
  String questionId = 'TG-BEPC-MATHS-2022-Q01',
  int repetitions = 0,
  double easinessFactor = 2.5,
  int intervalDays = 0,
  DateTime? nextReviewDate,
  int totalAttempts = 0,
  int correctAttempts = 0,
  bool isLearning = true,
}) {
  return ReviewCard(
    userId: userId,
    questionId: questionId,
    repetitions: repetitions,
    easinessFactor: easinessFactor,
    intervalDays: intervalDays,
    nextReviewDate: nextReviewDate ?? DateTime.now(),
    totalAttempts: totalAttempts,
    correctAttempts: correctAttempts,
    isLearning: isLearning,
  );
}

// ─── Widget pumping ────────────────────────────────────────────────

/// Pump [child] wrapped in a MaterialApp with the default mock providers.
///
/// Tests can override any provider by passing [overrides].
Future<void> pumpAppWithProviders(
  WidgetTester tester,
  Widget child, {
  AppUser? currentUser,
  SrsService? srsService,
  QuestionService? questionService,
  List<SingleChildWidget> overrides = const [],
}) async {
  final userProvider = FakeUserProvider(user: currentUser);
  await tester.pumpWidget(
    MultiProvider(
      providers: [
        ChangeNotifierProvider<UserProvider>.value(value: userProvider),
        Provider<SrsService>.value(value: srsService ?? MockSrsService()),
        Provider<QuestionService>.value(
          value: questionService ?? MockQuestionService(),
        ),
        ...overrides,
      ],
      child: MaterialApp(home: child),
    ),
  );
}
